services:
  - type: web
    name: llm-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: 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
        sync: false
